### ISSUE TITLE
no default export

### ISSUE THREAD

**Issue by PeterVos111** [AhmadiRamin/react-command-print#1]
after many tries, i finally got to npm install the app.

The right website opens, but does not show a new ribbon button. the only error that happens in the cmd after "gulp serve" 

This is the error:

Error - [tsc] src/extensions/print/components/print-dialog-content/print-dialog-content.tsx(3,8): error TS1192: Module '"C:/Users/User/source/repos/react-command-print/node_modules/react-to-print/lib/index"' has no default export.
[17:47:38] Error - 'tsc' sub task errored after 29 s
 exited with code 2

I don't know if these 2 are related or not. Hoping someone can help me.

**Comment by AhmadiRamin** [comment]
Hi @PeterVos111 
Unfortunately there is a problem with the latest version of react-to-print library, so just run these commands to solve the problem:

npm uninstall react-to-print
npm i react-to-print@2.0.0-alpha-4

I also updated the package.json to not use the latest version of this library.
Let me know if it solves your problem.

**Comment by PeterVos111** [comment]
Firstly, thanks for the quik response!

though  "gulp serve"now ran without any errors, first try got the button on the ribbon. When i clicked it, the pop-up showed up for 0,10 seconds and went away. The screen stayed grayed out until i clicked anywhere.

Second try didn't even get the button to show.

extra info; i had to delete the package-lock.js to run the npm install the first time i tried. The install created a new one.

**Comment by AhmadiRamin** [comment]
@PeterVos111 glad to hear that, I removed the package-lock.js so no one going to gets those errors again.
Regarding the pop-up issue, it's a bug I'm trying to fix, I haven't worked on this project for a while, maybe it's time to solve this problem.

**Comment by PeterVos111** [comment]
I would love a fix for that.  I'll keep checking for updates.

Yeah with the package-lock as original, the install would end up in ten's of files not being found
Just To be sure, as this is my first gulp app, the gulp command needs to be active for the app to work right?

**Comment by AhmadiRamin** [comment]
If you fixed it just make a pull request and I'll merge your changes.
Regarding the gulp, it's correct, you need to run gulp serve and when you apply your changes to the code it automatically update the app and you just need to refresh the page.

**Comment by AhmadiRamin** [comment]
@PeterVos111 I fixed the bug, it's really weird but is working! check out PrintCommandSet.ts, you can see this changes that I made to fix the issue:

dialog.show().then(()=>{
          Dialog.alert('This line prevents issues with the dialog, please do not remove it/');
        });

**Comment by PeterVos111** [comment]
@AhmadiRamin tried it yesterday. Had no changes. cmd opening as admin would make the button show, but it stayed at the grayed out screen. 
Today, i deleted the entire command-print file, re-cloned it, installed the 2.0 alpha, and did the Audit fix. 
No luck sadly. No print button even...    wondering if i forgot something. Only errors at the Npm install is a few deprecated ones

**Comment by AhmadiRamin** [comment]
Hi @PeterVos111 , I finally fixed the problem, sorry for late response, if you look at elements.xml in assets folder, ClientSideComponentId is not match with the Component Id, so I changed that and everything's working fine.
