### ISSUE TITLE
Document requirements for the mandatory "Print Settings List"

### ISSUE THREAD

**Issue by spencerstewart** [AhmadiRamin/react-command-print#2]
Hi Ramin,

First I want to say that this extension is amazing and very well done. I appreciate you sharing it with the SharePoint Developer Community.

I tried testing out this extension myself and it appears that a separate list to store print settings is required to make use of this extension. I can't find any clear references to the requirements for this list (i.e. column types). Would it be possible to include these details in the readme or wherever you think is most appropriate?

Many thanks!

**What I see:**
When I select a single item, there is the print icon. After clicking it, the modal shows up for a half second and then disappears leaving a darkly shaded background. If I click somewhere to dismiss the modal / shaded background, there is an Alert modal with no details.

**Error from console:**
`GET https://contoso.sharepoint.com/sites/BBMRIT/_api/web/lists/getByTitle('Print%20Settings%20List')/items?$filter=ListId%20eq%20%274ceabcc3-62e0-48a8-a19a-87b94fb6633e%27&$select=Id,Title,Header,Footer,Columns,ListId,HeaderAdvancedMode,FooterAdvancedMode,SkipBlankColumns 404`

**Comment by AhmadiRamin** [comment]
Hi Stewart,

Thank you for testing my extension, the required list is an asset you can find in SharePoint/Assets folder, when you add this app to a site this list created automatically but if you intend to test it by gulp serve you may need to create it manually based on the list schema you can find in the folder I mentioned before.

Best

**Comment by spencerstewart** [comment]
Ok, that's perfect. Thank you for the quick response. I was just testing it via gulp serve.

Thanks again!
